### PR TITLE
Fix mocking belongs_to associations in Rails 4.2+

### PR DESCRIPTION
**Pull request by JonRowe**
This #10 #11 #15 #19 updated for newer versions of ruby/rails.

Fixes #10 #11 #15 #19

### CODE REVIEW

**Comment by chrisbarber86** [comment]
Could we get a v1.0.2 gem release that includes this fix? cc @thomas-holmes

**Comment by thomas-holmes** [comment]
I can try to do it this weekend, or someone else can in my stead. I'm really busy with a new job at the moment!

**Comment by JonRowe** [comment]
@thomas-holmes I think you'd have to add us as owners of the gem to do that? Plus afaik only you, @myronmarston, and @samphippen can currently sign the gem.

**Comment by JonRowe** [comment]
Now released

**Comment by chrisbarber86** [comment]
Awesome, thanks guys!

**Pull request merged**
